FROM node:16-alpine

WORKDIR /app

# 复制package.json和package-lock.json (如果存在)
COPY package*.json ./

# 安装依赖
RUN npm ci

# 复制所有源代码
COPY . .

# 构建应用程序
ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
RUN npm run build

# 启动服务
CMD ["npm", "start"]